services:
  pdf-report-service:
    build: .
    container_name: pdf-report-service
    restart: unless-stopped
    shm_size: '1gb'
    env_file: .env
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdf-report.rule=Host(`pdf-report.srv808469.hstgr.cloud`)"
      - "traefik.http.routers.pdf-report.entrypoints=websecure"
      - "traefik.http.routers.pdf-report.tls=true"
      - "traefik.http.routers.pdf-report.tls.certresolver=mytlschallenge"
      - "traefik.http.services.pdf-report.loadbalancer.server.port=3000"

networks:
  root_default:
    external: true
